import sqlite3

def create_db():
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    # Creating a  Users table
    c.execute('''CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL
    )''')
    # Create Superheroes table
    c.execute('''CREATE TABLE IF NOT EXISTS superheroes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        image_url TEXT NOT NULL,
        video_url TEXT NOT NULL
    )''')
    # Preloading the superheroes table since it is empty
    c.execute('SELECT COUNT(*) FROM superheroes')
    if c.fetchone()[0] == 0:
        heroes = [
            ('Spider-Man', 
            'Peter Parker, a brilliant yet socially awkward teenager from Queens, New York, gained extraordinary powers after being bitten by a radioactive spider during a school science exhibit. As Spider-Man, he possesses superhuman strength, agility, and the ability to cling to walls, complemented by his web-shooters, which he designed using his scientific prowess. Peter’s journey as a hero is defined by the mantra “with great power comes great responsibility,” inspired by the tragic loss of his Uncle Ben, whose death at the hands of a criminal Peter failed to stop shaped his moral compass. Balancing his life as a high school student (later a photographer and scientist) with his crime-fighting duties, Peter faces villains like Green Goblin, Doctor Octopus, and Venom, often sacrificing personal relationships for the greater good. His quick wit, humor, and relatability make him a beloved everyman hero. Spider-Man is a core member of the Marvel Universe, frequently teaming up with the Avengers and Fantastic Four. His storylines, such as the “Clone Saga” and “Civil War,” explore themes of identity, sacrifice, and morality, cementing his legacy as a symbol of resilience and hope in Marvel Comics and beyond.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/133.jpg', 
            'https://www.youtube.com/embed/AZtwzbF0Jhw'),
            ('Superman', 
            'Kal-El, born on the doomed planet Krypton, was sent to Earth as an infant by his parents, Jor-El and Lara, to escape their world’s destruction. Raised as Clark Kent by Jonathan and Martha Kent in Smallville, Kansas, he discovered his extraordinary abilities—super strength, flight, x-ray vision, heat vision, super hearing, and near-invulnerability—stemming from Earth’s yellow sun. As Superman, he embodies hope and justice, protecting Metropolis and the world from threats like Lex Luthor, Brainiac, and Doomsday. Clark’s dual life as a mild-mannered reporter for the Daily Planet allows him to stay grounded, working alongside Lois Lane, his love interest, and Jimmy Olsen. His moral code, shaped by his adoptive parents, emphasizes selflessness and restraint, making him a beacon of heroism in the DC Universe. A founding member of the Justice League, Superman’s battles often explore themes of humanity, responsibility, and the struggle to belong as an alien among humans. Iconic storylines like “The Death of Superman” and “Kingdom Come” highlight his enduring impact as a symbol of truth and justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/791.jpg', 
            'https://www.youtube.com/embed/T6DJcgm3wNY'),
            ('Iron Man', 
            'Tony Stark, a billionaire industrialist and genius inventor, transformed his life after being kidnapped by terrorists and sustaining a life-threatening injury. Using his intellect, he built a powered suit of armor to escape, becoming Iron Man, a hero driven by technology and redemption. His suits, equipped with repulsors, flight capabilities, and advanced AI (JARVIS, later Vision), allow him to combat threats like the Mandarin, Whiplash, and Ultron. Tony’s personality—charismatic, arrogant, yet deeply principled—shapes his journey, as he grapples with alcoholism, corporate responsibility, and his role in the Avengers. As a founding member of the team, he often clashes with Captain America over ideology, notably in “Civil War.” Tony’s evolution from a self-serving playboy to a selfless hero reflects his complex character, blending wit with vulnerability. His technological innovations, such as the Bleeding Edge armor, and leadership in events like “Secret Invasion” make him a cornerstone of the Marvel Universe, with his storylines exploring themes of sacrifice, innovation, and the cost of power.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/85.jpg', 
            'https://www.youtube.com/embed/Ke1Y3P9D0Bc'),
            ('Wonder Woman', 
            'Diana Prince, born on the hidden island of Themyscira, is an Amazonian princess crafted from clay by her mother, Queen Hippolyta, and blessed by the gods with superhuman strength, speed, and wisdom. Wielding the Lasso of Truth, indestructible bracelets, and a tiara that doubles as a weapon, she fights for peace and equality in the world of man. Leaving her idyllic home to combat Ares, the god of war, Diana becomes Wonder Woman, a symbol of compassion and strength. As a founding member of the Justice League, she faces villains like Cheetah, Circe, and Darkseid, often mediating conflicts with her diplomatic skills. Her dual role as a warrior and ambassador reflects her commitment to justice and love, shaped by her Amazonian upbringing. Key storylines like “Gods and Mortals” and “War of the Gods” explore her divine heritage and moral dilemmas, making her a feminist icon and a pillar of the DC Universe. Diana’s empathy, resilience, and unyielding spirit inspire hope, bridging mortal and divine realms.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/807.jpg', 
            'https://www.youtube.com/embed/VSB4wGIdDwo'),
            ('Invincible', 
            'Mark Grayson, a teenager from Earth, is the son of Omni-Man, a superhero from the planet Viltrum. As Invincible, Mark develops superhuman strength, speed, flight, and near-invulnerability as his Viltrumite heritage awakens. Guided by his father, he begins his heroic journey, protecting Earth from threats like the Mauler Twins, Titan, and the Viltrumite Empire. Mark’s optimistic and determined personality shines through, but his naivety is tested by betrayals and moral complexities, notably in the “Invincible War” and “The Viltrumite War” storylines. Balancing high school, relationships, and heroism, Mark grows into a seasoned hero, joining teams like the Guardians of the Globe. His struggles with loss, identity, and the cost of power make him a relatable figure in Image Comics. Unlike traditional heroes, Mark’s journey is grounded in gritty realism, with visceral battles and emotional depth, cementing his status as a modern superhero icon.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10866.jpg', 
            'https://www.youtube.com/embed/-bfAVpuko5o'),
            # ... Full list of 100 heroes follows (abridged for brevity)
            ('Captain America', 
            'Steve Rogers, a frail young man from Brooklyn, was transformed into a super-soldier during World War II through an experimental serum, granting him peak human strength, agility, and endurance. Wielding an indestructible vibranium shield, he became Captain America, a symbol of freedom and resilience. Initially fighting Nazis alongside the Invaders, Steve was frozen in ice after a mission, awakening decades later to lead the Avengers in the modern era. His unwavering moral code and leadership shine in battles against Hydra, Red Skull, and Thanos. Storylines like “The Winter Soldier” and “Civil War” explore his loyalty, sacrifice, and clashes with Tony Stark over individual freedoms. Steve’s selflessness, rooted in his Depression-era upbringing, makes him a timeless hero, inspiring allies and fans alike with his unyielding commitment to justice and equality in the Marvel Universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/274.jpg', 
            'https://www.youtube.com/embed/cs8rF8dR8gY'),
            ('Thor', 
            'Thor Odinson, the Norse God of Thunder and prince of Asgard, wields the enchanted hammer Mjolnir, granting him control over lightning, storms, and immense strength. Born to Odin and Frigga, Thor’s journey from arrogant warrior to selfless protector defines his arc. Banished to Earth to learn humility, he becomes a guardian of Midgard, facing threats like Loki, Malekith, and Hela. As an Avenger, Thor’s battles in “Ragnarok” and “Infinity War” showcase his resilience and evolving sense of duty. His blend of divine power and human empathy—forged through relationships with Jane Foster and the Avengers—makes him a complex hero. Thor’s cosmic adventures, including defending the Nine Realms and confronting Gorr the God Butcher, explore themes of legacy, sacrifice, and redemption, solidifying his status as a mythic figure in Marvel Comics.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/140.jpg', 
            'https://www.youtube.com/embed/JOddp-nlNvQ'),
            ('Hulk', 
            'Dr. Bruce Banner, a brilliant scientist, was exposed to gamma radiation during a bomb test, transforming him into the Hulk, a green behemoth with unmatched strength that increases with rage. Struggling to control his alter ego, Bruce’s life is a constant battle between intellect and raw power. As the Hulk, he faces villains like the Abomination, Leader, and Maestro, often causing destruction despite his heroic intentions. A founding Avenger, Hulk’s alliances shift due to his volatile nature, seen in storylines like “Planet Hulk” and “World War Hulk,” where he’s both hero and outcast. Bruce’s tragic past, marked by childhood trauma, fuels his inner conflict, making him a complex figure. His gamma-powered durability, speed, and regeneration make him a force of nature, while his quest for peace and acceptance resonates with fans, cementing his place as a Marvel icon.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/83.jpg', 
            'https://www.youtube.com/embed/ZyJ3k6jBRcs'),
            ('Black Panther', 
            'T’Challa, king of the secretive African nation Wakanda, gains enhanced strength, agility, and senses from the heart-shaped herb, a gift from the panther god Bast. As Black Panther, he protects his people and the world, wielding vibranium technology, including his iconic suit. Trained as a warrior and diplomat, T’Challa balances leadership with heroism, facing foes like Killmonger, Klaw, and Namor. His reign is marked by challenges to Wakanda’s isolationist traditions, as seen in “A Nation Under Our Feet” and “Avengers vs. X-Men.” A key Avenger and Illuminati member, T’Challa’s intellect and moral resolve make him a global leader. His cultural impact, rooted in African heritage and advanced technology, redefines superhero narratives, emphasizing sovereignty and responsibility. T’Challa’s journey explores themes of duty, legacy, and unity, making him a pivotal figure in Marvel Comics.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/247.jpg', 
            'https://www.youtube.com/embed/xjDjIWPwcPU'),
            ('Wolverine', 
            'James “Logan” Howlett, a mutant with a regenerative healing factor and adamantium-laced skeleton, is one of Marvel’s most enduring heroes. Born in 19th-century Canada, Logan’s long life is marked by tragedy—losing family, lovers, and memories to war and experimentation. His adamantium claws, superhuman senses, and combat skills make him a lethal fighter, battling foes like Sabretooth, Magneto, and Weapon X. As an X-Men member, Logan’s gruff exterior hides a loyal heart, seen in his mentorship of young mutants like Kitty Pryde and Jubilee. Storylines like “Old Man Logan” and “Death of Wolverine” explore his resilience and mortality. Logan’s internal struggle—balancing his animalistic instincts with his humanity—defines his character, making him a fan-favorite anti-hero whose grit and redemption resonate across the Marvel Universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/161.jpg', 
            'https://www.youtube.com/embed/Div0iP65aZo'),
            ('Doctor Strange', 
            'Stephen Strange, once a brilliant but arrogant neurosurgeon, lost his hands’ dexterity in a car accident, leading him to seek healing in Kamar-Taj. Trained by the Ancient One, he became the Sorcerer Supreme, mastering mystic arts to protect Earth from magical threats like Dormammu, Baron Mordo, and Nightmare. Wielding the Eye of Agamotto (housing the Time Stone), Cloak of Levitation, and spells, Strange manipulates reality, time, and dimensions. His intellect and newfound humility guide his battles, as seen in “The Oath” and “Infinity War.” As an Avenger and Illuminati member, Strange’s cosmic adventures explore mysticism and sacrifice. His complex personality— blending wit, determination, and moral growth—makes him a cornerstone of Marvel’s supernatural narratives, defending reality with unparalleled arcane knowledge.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/12.jpg', 
            'https://www.youtube.com/embed/Lt-U_t2pUHI'),
            ('Scarlet Witch', 
            'Wanda Maximoff, a mutant with chaos magic, can alter reality, manipulate probabilities, and unleash devastating energy. Born in Sokovia and raised with her brother Pietro (Quicksilver), Wanda’s powers emerged through trauma and experimentation, later enhanced by the Mind Stone. Initially a villain alongside Magneto, she joined the Avengers, facing foes like Ultron and Thanos. Her love for Vision and tragic losses drive her arc, notably in “House of M,” where she reshaped reality, and “WandaVision,” exploring grief and identity. Wanda’s volatile powers and emotional depth make her a complex hero, balancing immense strength with vulnerability. Her journey through sacrifice, redemption, and the consequences of power positions her as one of Marvel’s most compelling figures, redefining reality itself.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/444.jpg', 
            'https://www.youtube.com/embed/sj9J2ecsSpo'),
            ('Deadpool', 
            'Wade Wilson, a former Special Forces operative turned mercenary, gained rapid healing and near-immortality after undergoing torturous experiments in the Weapon X program to cure his cancer. As Deadpool, he wields katanas, guns, and a razor-sharp wit, breaking the fourth wall with his irreverent humor. Facing villains like Ajax and Cable, Wade’s chaotic heroism blends violence with comedy, as seen in “Deadpool Kills the Marvel Universe” and his X-Force tenure. His friendships with Spider-Man and Wolverine, plus his love for Vanessa, ground his anarchic persona. Deadpool’s regenerative abilities, combat skills, and unpredictable nature make him a unique anti-hero, beloved for his defiance of superhero tropes and relentless optimism despite a tragic past.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/835.jpg', 
            'https://www.youtube.com/embed/ONHBaC-pfsk'),
            ('Black Widow', 
            'Natasha Romanoff, a Russian orphan trained in the Red Room as a Black Widow assassin, defected to SHIELD, becoming a master spy and martial artist. With no superpowers, her agility, combat skills, and gadgets like Widow’s Bite make her formidable against foes like Taskmaster and Red Guardian. Natasha’s complex past, marked by espionage and redemption, shapes her role as an Avenger, seen in “The Avengers” and “Black Widow.” Her loyalty to friends like Clint Barton and Steve Rogers, plus her self-sacrifice in “Endgame,” highlight her heroism. Natasha’s blend of cunning, resilience, and humanity makes her a standout Marvel hero, navigating a world of spies and superhumans with unmatched skill and heart.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/217.jpg', 
            'https://www.youtube.com/embed/ybLTDShQfOY'),
            ('Hawkeye', 
            'Clint Barton, a skilled archer and former circus performer, became Hawkeye after mastering trick arrows and hand-to-hand combat. Working for SHIELD and later the Avengers, he faces villains like Loki and the Tracksuit Mafia with precision and grit. His grounded perspective, loyalty to Natasha Romanoff, and family life anchor his character, as seen in “The Avengers” and “Hawkeye.” Despite lacking superpowers, Clint’s resourcefulness and determination shine, notably in “Civil War” and his Ronin phase post-“Endgame.” His mentorship of Kate Bishop ensures his legacy. Hawkeye’s everyman charm, sharpshooting prowess, and unyielding spirit make him a vital Marvel hero, proving skill can rival superpowers.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/88.jpg', 
            'https://www.youtube.com/embed/5VYb3B1ETlk'),
            ('Ant-Man', 
            'Scott Lang, a former thief, became Ant-Man after inheriting the Pym Particle suit from Hank Pym, allowing him to shrink to insect size or grow to giant proportions while retaining superhuman strength. With his Ant-Man helmet, he communicates with ants, using them strategically in battles against foes like Yellowjacket and Kang. Scott’s humor, ingenuity, and redemption arc—balancing heroism with fatherhood to Cassie Lang—define his role in the Avengers, seen in “Ant-Man” and “Endgame.” His quantum realm expertise proves pivotal in “Quantumania.” Scott’s underdog charm and creative use of size manipulation make him a unique Marvel hero, proving even the smallest can change the world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/857.jpg', 
            'https://www.youtube.com/embed/pWdKf3MneyI'),
            ('Captain Marvel', 
            'Carol Danvers, a former Air Force pilot, gained cosmic powers after exposure to the Kree Tesseract, becoming Captain Marvel with super strength, flight, and energy blasts. Mentored by Mar-Vell, she protects Earth and the galaxy from threats like the Kree, Skrulls, and Thanos. Her resilience and leadership shine in “Captain Marvel” and “The Marvels,” where she teams with Monica Rambeau and Kamala Khan. Carol’s journey explores identity, duty, and empowerment, shaped by her military background and cosmic destiny. As an Avenger, her near-limitless power and determination make her a galactic guardian, redefining heroism in the Marvel Universe with her unyielding spirit and compassion.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/112.jpg', 
            'https://www.youtube.com/embed/Z1BCujX3pw8'),
            ('Storm', 
            'Ororo Munroe, born in Harlem and raised in Cairo, is a mutant with the power to control weather—summoning storms, lightning, and winds with godlike precision. Orphaned and later worshipped as a goddess in Africa, she joined the X-Men, becoming a leader alongside Cyclops. Facing foes like Magneto and the Shadow King, Storm’s strength, empathy, and regal presence shine, as seen in “Lifedeath” and “X-Men: Apocalypse.” Her marriage to T’Challa and role in “X-Men: Red” highlight her diplomatic and heroic qualities. Storm’s blend of elemental power and compassion, rooted in her diverse heritage, makes her a pivotal mutant hero, inspiring unity and resilience in the Marvel Universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/135.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Vision', 
            'Created by Ultron and Tony Stark using the Mind Stone and JARVIS, Vision is a synthetic being with density manipulation, flight, and energy projection. His Vibranium body and artificial intelligence make him a unique Avenger, battling threats like Ultron and Thanos. Vision’s romance with Scarlet Witch, explored in “WandaVision,” reveals his struggle to understand humanity and love, blending logic with emotion. His philosophical nature and sacrifice in “Infinity War” highlight his selflessness. Vision’s quest for identity and morality, coupled with his immense power, positions him as a key Marvel hero, navigating the line between machine and man with profound insight.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/271.jpg', 
            'https://www.youtube.com/embed/1yDZaY_kf3Q'),
            ('Daredevil', 
            'Matt Murdock, blinded as a child by radioactive chemicals, gained enhanced senses—radar-like perception, acute hearing, and agility—becoming Daredevil, Hell’s Kitchen’s vigilante. A skilled lawyer by day, he fights crime by night, wielding batons and martial arts against Kingpin, Bullseye, and the Hand. Raised Catholic, Matt’s faith and guilt drive his dual life, as seen in “Born Again” and “Guardian Devil.” His resilience against personal losses—like Elektra’s death—and his gritty heroism make him a street-level icon. Daredevil’s blend of legal acumen, acrobatic prowess, and moral complexity defines him as a Marvel hero who protects his city with unwavering determination.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/70.jpg', 
            'https://www.youtube.com/embed/jAy6NJ_D5vU'),
            ('Ghost Rider', 
            'Johnny Blaze, a stunt motorcyclist, sold his soul to Mephisto to save his father, becoming Ghost Rider, a supernatural anti-hero with a flaming skull and hellfire powers. Riding a blazing motorcycle, he punishes the guilty with his Penance Stare, facing demons like Blackheart and Zarathos. His cursed existence and battles in “Spirit of Vengeance” and “Midnight Sons” explore themes of redemption and vengeance. Johnny’s struggle to control his demonic side while protecting the innocent makes him a unique Marvel hero, blending horror and heroism with a fiery, relentless drive to deliver justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/74.jpg', 
            'https://www.youtube.com/embed/L0CK69f0YpU'),
            ('Silver Surfer', 
            'Norrin Radd, a scholar from Zenn-La, became the Silver Surfer to save his planet, serving Galactus as a herald with the Power Cosmic, granting him flight, energy manipulation, and cosmic awareness. Surfing the stars on his silver board, he rebelled against Galactus to protect Earth, facing threats like Thanos and Annihilus. His philosophical nature and cosmic perspective, seen in “Silver Surfer: Requiem” and “Annihilation,” explore themes of freedom and sacrifice. Norrin’s selflessness and quest for meaning make him a profound Marvel hero, navigating the universe with grace and power, seeking redemption for his past.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/127.jpg', 
            'https://www.youtube.com/embed/5xY3S9S9f9g'),
            ('Namor', 
            'Namor McKenzie, the Sub-Mariner, is the mutant prince of Atlantis, born to a human father and Atlantean mother. With superhuman strength, flight, and aquatic abilities, he rules the seas, often clashing with surface-dwellers like the Fantastic Four or aiding them against threats like Attuma and Tiger Shark. His pride and loyalty to Atlantis, seen in “Defenders” and “Invaders,” make him a complex hero, oscillating between ally and antagonist. Namor’s regal demeanor, environmental advocacy, and struggles with human-Atlantean relations define his legacy, making him a pivotal Marvel figure who balances power with duty.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/142.jpg', 
            'https://www.youtube.com/embed/8zQvk2L8dMo'),
            ('Jean Grey', 
            'Jean Grey, a powerful mutant with telepathy and telekinesis, became one of the X-Men’s core members, trained by Professor Xavier. Hosting the Phoenix Force, a cosmic entity, she gained near-omnipotent powers, reshaping reality in “Dark Phoenix Saga.” Her battles against Magneto, Apocalypse, and her own Phoenix persona explore themes of control and sacrifice. Jean’s compassion, intelligence, and love for Cyclops and Wolverine ground her, despite cosmic struggles. Her resurrection cycles and leadership in “X-Men: Red” highlight her resilience. Jean’s journey as a mutant and cosmic force makes her a Marvel icon, embodying the struggle between humanity and godlike power.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/151.jpg', 
            'https://www.youtube.com/embed/6XBs1N-1U8o'),
            ('Star-Lord', 
            'Peter Quill, a half-human, half-Spartoi adventurer, leads the Guardians of the Galaxy as Star-Lord, wielding dual element guns and a high-tech helmet. Raised by space pirates after his mother’s death, Peter’s roguish charm and leadership shine against foes like Thanos, Ronan, and Ego. His love for Gamora and bonds with Rocket, Groot, and Drax drive his arc, seen in “Guardians of the Galaxy” and “Infinity War.” Peter’s wit, bravery, and knack for improvisation make him a cosmic hero, navigating galactic threats with a mix of humor and heart, redefining leadership in the Marvel Universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10353.jpg', 
            'https://www.youtube.com/embed/d96cjJhvlMA'),
            ('Gamora', 
            'Gamora Zen Whoberi Ben Titan, raised by Thanos as an assassin, became the deadliest woman in the galaxy before joining the Guardians of the Galaxy. With superhuman strength, agility, and combat skills, she wields her sword against threats like Nebula, Ronan, and Thanos himself. Her redemption arc, driven by her rejection of Thanos’ cruelty, shines in “Guardians of the Galaxy” and “Infinity War.” Gamora’s loyalty to Peter Quill and her struggle for identity make her a compelling hero. Her Zen-Whoberi heritage and warrior spirit position her as a key Marvel figure, fighting for freedom and justice across the cosmos.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/165.jpg', 
            'https://www.youtube.com/embed/2Svi37Z28KM'),
            ('Rocket Raccoon', 
            'Rocket, a genetically engineered raccoon from Halfworld, is a master tactician, sharpshooter, and tech genius, wielding heavy weaponry with the Guardians of the Galaxy. Despite his small size, his ferocity and loyalty shine against foes like Ronan and the High Evolutionary. His tragic origin—subjected to cruel experiments—fuels his cynical yet caring nature, seen in “Guardians of the Galaxy Vol. 3.” Rocket’s bond with Groot and leadership in “Infinity War” highlight his growth from loner to hero. His ingenuity and heart make him a standout Marvel character, proving courage transcends size in cosmic battles.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10038.jpg', 
            'https://www.youtube.com/embed/jiGkrGGk9q0'),
            ('Groot', 
            'Groot, a tree-like Flora colossus from Planet X, possesses regenerative powers, super strength, and the ability to grow and manipulate his wooden body. Known for saying “I am Groot,” he communicates profound emotions through tone, forming a deep bond with Rocket and the Guardians of the Galaxy. Facing threats like Ronan and Thanos, Groot’s selflessness shines, notably sacrificing himself in “Guardians of the Galaxy.” His rebirth as Baby Groot and growth in “Vol. 2” explore themes of family and growth. Groot’s gentle giant persona and unwavering loyalty make him a beloved Marvel hero, embodying sacrifice and connection.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10037.jpg', 
            'https://www.youtube.com/embed/D54rCcc2C4c'),
            ('Batman', 
            'Bruce Wayne, orphaned after his parents’ murder in Gotham, trained for years to become Batman, the Dark Knight. Using his intellect, martial arts mastery, and vast wealth, he employs gadgets like the Batarang and Batmobile to fight crime. Facing villains like the Joker, Bane, and Ra’s al Ghul, Batman’s no-kill rule and detective skills define his mission, seen in “The Dark Knight Returns” and “Court of Owls.” As a Justice League founder, he counters superhuman threats with strategy, often outsmarting gods like Darkseid. Bruce’s trauma and relentless drive make him a complex DC hero, symbolizing human resilience and justice without superpowers.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/639.jpg', 
            'https://www.youtube.com/embed/rgH2w2N4zEA'),
            ('The Flash', 
            'Barry Allen, a forensic scientist, gained super speed after a lightning strike and chemical accident, becoming the Flash, the Scarlet Speedster. Able to run near light speed, vibrate through objects, and travel time, he protects Central City from foes like Reverse-Flash, Gorilla Grodd, and Zoom. His optimism and scientific mind shine in “Flashpoint,” where he alters reality, and “Crisis on Infinite Earths,” saving the multiverse. A Justice League member, Barry’s selflessness and humor make him a fan-favorite. His speed and heart redefine heroism, proving even the fastest man alive values every moment in the DC Universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/892.jpg', 
            'https://www.youtube.com/embed/Yj0l7drA9f4'),
            ('Aquaman', 
            'Arthur Curry, half-human, half-Atlantean, is the king of Atlantis, wielding super strength, aquatic telepathy, and the Trident of Neptune. Raised on land, he embraced his heritage to protect the seas and surface world from threats like Ocean Master, Black Manta, and the Trench. His leadership in “Throne of Atlantis” and “Justice League” showcases his regal yet relatable nature. Arthur’s struggle to unite two worlds, seen in “Aquaman” and “Drowned Earth,” highlights his diplomacy and strength. A Justice League stalwart, Aquaman’s environmental advocacy and warrior spirit make him a vital DC hero, redefining the oceans’ might.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/277.jpg', 
            'https://www.youtube.com/embed/WDkg3h8PCVU'),
            ('Green Lantern', 
            'Hal Jordan, a test pilot, was chosen by the Green Lantern Corps’ ring to wield willpower-fueled energy constructs, flight, and protection. Protecting Sector 2814, he faces threats like Sinestro, Parallax, and Atrocitus, often with the Justice League. His fearless attitude and creativity shine in “Emerald Twilight” and “Blackest Night,” where he battles cosmic evil. Hal’s journey from reckless pilot to Corps leader explores redemption and duty. His ring’s versatility and unyielding spirit make him a cornerstone of DC’s cosmic narratives, proving willpower can overcome any fear in the universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/698.jpg', 
            'https://www.youtube.com/embed/FrkM3QpT7kY'),
            ('Shazam', 
            'Billy Batson, a foster child, was granted powers by the wizard Shazam, transforming into a magical champion with the strength of Hercules, stamina of Atlas, and wisdom of Solomon. Saying “Shazam!” summons lightning to access flight, super strength, and energy projection. Facing foes like Black Adam and Dr. Sivana, Billy’s youthful optimism shines in “The Power of Shazam!” and “Justice League.” His journey explores maturity and family, balancing a child’s heart with godlike power. A Justice League member, Billy’s infectious joy and heroism make him a unique DC hero, embodying hope and transformation.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/838.jpg', 
            'https://www.youtube.com/embed/go6GEIrcvFY'),
            ('Nightwing', 
            'Dick Grayson, the first Robin, became Nightwing after leaving Batman’s shadow, using acrobatics, martial arts, and Escrima sticks to protect Blüdhaven. Trained by Batman, his detective skills and leadership shine against foes like Blockbuster and Deathstroke. His time with the Teen Titans and “Nightwing: Year One” highlight his growth into a charismatic leader. Dick’s optimism and loyalty, seen in “Batman: Reborn” as a temporary Batman, make him a fan-favorite. His circus roots and bonds with the Bat-family define his journey, proving he’s a DC hero who thrives independently while honoring his legacy.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/853.jpg', 
            'https://www.youtube.com/embed/1o-4aV5nJZs'),
            ('Cyborg', 
            'Victor Stone, a teen athlete, was rebuilt with advanced cybernetics after a lab accident, becoming Cyborg, a half-human, half-machine hero. With super strength, tech interfacing, and weaponry like sonic cannons, he battles threats like Brother Blood and Grid. A Teen Titans and Justice League member, Victor’s journey in “Cyborg: Rebirth” explores identity and humanity, grappling with his dual nature. His tech expertise and resilience shine in “Justice League” and “Doom Patrol.” Cyborg’s blend of strength, intellect, and heart makes him a vital DC hero, bridging man and machine in the fight for justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/672.jpg', 
            'https://www.youtube.com/embed/rCyY09V0VGA'),
            ('Green Arrow', 
            'Oliver Queen, a billionaire playboy, became Green Arrow after being stranded on an island, mastering archery and survival. Using trick arrows and martial arts, he protects Star City from villains like Merlyn and Prometheus. His liberal activism and romance with Black Canary define his arc, seen in “Green Arrow: Year One” and “Longbow Hunters.” A Justice League member, Oliver’s wit and resourcefulness shine despite no superpowers. His journey explores redemption and social justice, making him a grounded DC hero who fights for the underdog with unerring precision and heart.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/696.jpg', 
            'https://www.youtube.com/embed/4p-E_2RaNvg'),
            ('Martian Manhunter', 
            'J’onn J’onzz, the last Martian, fled his planet’s destruction to Earth, becoming the Martian Manhunter with shape-shifting, telepathy, and super strength. As a Justice League founder, he faces threats like White Martians and Despero, using his detective skills and empathy. His outsider perspective and loss, seen in “A New Beginning” and “Final Crisis,” explore themes of belonging and sacrifice. J’onn’s calm wisdom and versatility make him a cornerstone of DC, blending alien powers with a deep connection to humanity, protecting Earth as a guardian of peace.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/733.jpg', 
            'https://www.youtube.com/embed/ueZwv1bW5ng'),
            ('Hawkman', 
            'Carter Hall, a reincarnated Egyptian prince, wields Nth metal wings, super strength, and ancient weapons as Hawkman. With memories of past lives, he fights alongside Hawkgirl against foes like Hath-Set and Shadow Thief. His archaeological expertise and warrior spirit shine in “The Savage Hawkman” and “Justice Society of America.” A Justice League member, Carter’s eternal bond with Shiera and relentless courage define him. His complex history across reincarnations explores fate and love, making Hawkman a timeless DC hero who soars through history with unyielding resolve.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/706.jpg', 
            'https://www.youtube.com/embed/9eY-P1V0n0Q'),
            ('Hawkgirl', 
            'Shiera Sanders, Hawkman’s eternal partner, wields Nth metal wings and weapons, granting flight and super strength. Reincarnated across centuries, she fights alongside Carter against villains like Vandal Savage. Her fierce spirit and combat prowess shine in “Justice Society” and “Blackest Night.” Shiera’s balance of warrior instinct and compassion, seen in “Hawkworld,” makes her a compelling DC hero. Her love for Carter and defiance of fate define her journey, blending ancient legacy with modern heroism, soaring as a symbol of strength and partnership.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/707.jpg', 
            'https://www.youtube.com/embed/8kS7A_3Zm4o'),
            ('Zatanna', 
            'Zatanna Zatara, a magician with spell-casting powers, speaks backwards to wield magic, inherited from her father, Giovanni Zatara. A Justice League Dark member, she battles supernatural threats like Constantine’s foes and Eclipso. Her stage performer charisma and mystical knowledge shine in “Seven Soldiers” and “Books of Magic.” Zatanna’s struggle to balance her heroic duties with personal losses, like her father’s death, defines her arc. Her blend of showmanship, power, and vulnerability makes her a standout DC hero, enchanting allies and foes alike with her magical prowess and heart.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/809.jpg', 
            'https://www.youtube.com/embed/2X7V2wusI4Y'),
            ('Blue Beetle', 
            'Jaime Reyes, a teen from El Paso, bonded with an alien scarab, gaining a high-tech suit with weapons, flight, and energy blasts. As Blue Beetle, he protects his city from foes like the Reach and Black Beetle. His youthful optimism and family ties shine in “Blue Beetle: Graduation Day” and “Infinite Crisis.” A Teen Titans member, Jaime’s journey explores responsibility and heritage, balancing heroism with everyday life. His scarab’s sentience and his own courage make him a unique DC hero, wielding alien tech with a human heart.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/864.jpg', 
            'https://www.youtube.com/embed/v3evsR2KDiY'),
            ('Firestorm', 
            'Ronnie Raymond and Martin Stein merge via a nuclear accident to become Firestorm, with powers to transmute matter and project energy. Facing villains like Multiplex and Killer Frost, their dual consciousness creates dynamic teamwork, seen in “The Nuclear Man” and “Brightest Day.” A Justice League member, Firestorm’s scientific mind and fiery spirit shine. Their struggle to balance two minds and wield godlike power explores identity and cooperation, making Firestorm a vibrant DC hero who transforms challenges into victories with nuclear might.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/704.jpg', 
            'https://www.youtube.com/embed/5kS2b7v3f0o'),
            ('Atom', 
            'Ray Palmer, a physicist, uses a dwarf star fragment to shrink to microscopic sizes as the Atom, retaining strength and agility. Fighting foes like Chronos and Bug-Eyed Bandit, he explores subatomic realms, seen in “Sword of the Atom” and “Identity Crisis.” A Justice League member, Ray’s intellect and courage make him a versatile hero. His journey through loss and scientific discovery defines his arc, blending brain and brawn. The Atom’s ability to navigate the unseen world makes him a unique DC hero, shrinking the gap between science and heroism.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/717.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Black Canary', 
            'Dinah Lance, a martial artist with a sonic “Canary Cry,” fights crime in Star City alongside Green Arrow. Trained by Wildcat, her combat skills and metahuman scream take on foes like Count Vertigo and White Canary. Her leadership in the Birds of Prey and Justice League, seen in “Birds of Prey” and “Green Arrow/Black Canary,” showcases her tenacity. Dinah’s blend of grit, compassion, and musical flair defines her, making her a street-level DC hero whose voice and fists deliver justice with equal force.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/667.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Red Tornado', 
            'Red Tornado, an android created by T.O. Morrow, wields wind manipulation and super strength, joining the Justice League to fight villains like Amazo and Starbreaker. His quest for humanity, seen in “Red Tornado” and “Young Justice,” explores identity and free will. Despite his mechanical nature, his loyalty and sacrifice shine, notably in “Crisis on Earth-Two.” Red Tornado’s struggle to connect with humans while battling as a hero makes him a unique DC figure, embodying the heart of a machine in a whirlwind of justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1103.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Omni-Man', 
            'Nolan Grayson, a superhero from Viltrum, possesses super strength, speed, and flight, sent to Earth to prepare it for his empire’s conquest. Posing as a hero, he mentors his son Mark (Invincible) but betrays Earth, revealed in “Invincible.” His redemption arc, battling Viltrumites and aiding Mark, explores loyalty and morality. Nolan’s complex motives and familial bonds make him a compelling Image Comics hero, balancing galactic duty with personal growth, fighting for redemption in a universe of conflict.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10867.jpg', 
            'https://www.youtube.com/embed/3eU7bSc2U8o'),
            ('Spawn', 
            'Al Simmons, a murdered CIA operative, made a deal with Malebolgia to return as Spawn, a hellspawn with necromantic powers, chains, and a living cape. Fighting demons, angels, and mobsters like Violator, his journey in “Spawn” and “Curse of the Spawn” explores vengeance and redemption. His struggle to retain humanity while wielding supernatural power makes him a dark Image Comics hero. Spawn’s gritty battles and moral complexity redefine anti-heroism, blending horror and heroism in a relentless fight against evil.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/790.jpg', 
            'https://www.youtube.com/embed/0kS2b7v3f0o'),
            ('Hellboy', 
            'Anung Un Rama, a demon summoned by Nazis but raised by the B.P.R.D., became Hellboy, wielding super strength, a stone hand, and occult knowledge. Fighting monsters like Rasputin and the Ogdru Jahad, his adventures in “Seed of Destruction” and “Hellboy in Hell” blend horror and heroism. His sarcastic wit and loyalty to humanity shine, despite his demonic origins. Hellboy’s quest to defy his apocalyptic destiny makes him a Dark Horse icon, battling the supernatural with grit and heart in a world of darkness.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1026.jpg', 
            'https://www.youtube.com/embed/dt5g5_1cKVk'),
            ('The Tick', 
            'The Tick, a comedic hero with super strength and near-invulnerability, protects The City with his sidekick Arthur. Facing absurd villains like Chairface Chippendale, his over-the-top optimism and catchphrases shine in “The Tick” and “Spoon!” His lack of a clear origin adds to his quirky charm, parodying superhero tropes. A protector with a childlike heart, The Tick’s humor and bravery make him a unique indie hero, delivering justice with a larger-than-life personality in a world of absurdity.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1082.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Savage Dragon', 
            'Savage Dragon, a green-skinned amnesiac with super strength and healing, fights crime in Chicago as a police officer. Created by Erik Larsen, his battles against Overlord and the Vicious Circle explore grit and duty in “Savage Dragon.” His struggle to uncover his origins and protect his family grounds his arc. Dragon’s raw power and no-nonsense attitude make him an Image Comics staple, blending superhero action with street-level realism, delivering justice with fists and heart in a chaotic world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1081.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('ShadowHawk', 
            'Paul Johnstone, a vigilante with a high-tech armored suit, became ShadowHawk to fight crime in New York. With enhanced strength and agility, he battles foes like Vendetta in “ShadowHawk.” His mysterious past and relentless pursuit of justice echo Batman, but his darker methods set him apart. ShadowHawk’s journey in Image Comics explores vengeance and morality, making him a gritty hero who operates in the shadows, delivering justice with precision and force in a crime-ridden city.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1083.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Witchblade', 
            'Sara Pezzini, an NYPD detective, bonded with the Witchblade, a mystical gauntlet granting super strength, armor, and energy blasts. Fighting supernatural threats like the Darkness, her journey in “Witchblade” explores power and responsibility. Sara’s tough demeanor and moral compass shine, balancing her detective work with cosmic battles. The Witchblade’s sentience challenges her autonomy, making her a complex Image Comics hero. Her blend of grit, mysticism, and humanity redefines heroism, wielding ancient power in a modern world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1084.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('The Maxx', 
            'The Maxx, a homeless man with dream-world powers, protects Julie Winters in a surreal reality, battling Mr. Gone and Isz. His dual existence in the real world and the Outback, seen in “The Maxx,” explores trauma and identity. His super strength and loyalty to Julie make him a tragic hero. The Maxx’s psychedelic narrative and emotional depth make him a unique Image Comics figure, fighting surreal threats with a broken yet heroic heart in a fractured reality.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1085.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Atom Eve', 
            'Samantha Eve Wilkins, a hero from Invincible, manipulates matter at the atomic level, creating constructs and altering reality. Raised in a lab, she joins the Teen Team and Guardians of the Globe, facing Viltrumites and Omni-Man. Her romance with Mark Grayson and growth in “Invincible” highlight her compassion and strength. Eve’s struggle for identity and purpose, seen in “Atom Eve Special,” makes her a standout Image Comics hero, wielding godlike power with a human heart, reshaping the world for good.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10868.jpg', 
            'https://www.youtube.com/embed/3eU7bSc2U8o'),
            ('SuperPatriot', 
            'John Armstrong, a WWII super-soldier turned cyborg, became SuperPatriot with enhanced strength and weaponry. Fighting villains like the Covenant of the Sword in “Savage Dragon,” his patriotism and resilience shine. His cybernetic upgrades and moral code make him a gritty Image Comics hero, balancing duty with survival. SuperPatriot’s journey explores sacrifice and legacy, delivering justice with high-tech power in a world of chaos, standing as a symbol of enduring heroism.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1087.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Battle Beast', 
            'A lion-like warrior from Invincible, Battle Beast seeks worthy opponents with his immense strength and combat skill. Initially a villain, his honor and desire for challenge lead him to aid Mark Grayson against Viltrumites. His arc in “Invincible” explores purpose and redemption, making him a complex anti-hero. Battle Beast’s ferocity and warrior code make him a standout Image Comics figure, fighting epic battles with a heart driven by the thrill of combat and a quest for meaning.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10869.jpg', 
            'https://www.youtube.com/embed/3eU7bSc2U8o'),
            ('Firebreather', 
            'Duncan Rosenblatt, a half-human, half-dragon teen, wields fire-based powers and super strength as Firebreather. Facing prejudice and foes like Belloc, his father, his journey in “Firebreather” explores identity and acceptance. A young hero in Image Comics, Duncan’s struggle to balance his monstrous heritage with his human heart makes him compelling. His fiery powers and determination to prove himself shine, forging a path as a unique hero who breathes fire into the fight for justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1088.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Kid Omni-Man', 
            'Oliver Grayson, Mark’s half-Viltrumite brother, develops super strength and flight as Kid Omni-Man. Raised on Earth, he joins the fight against Viltrumites, seen in “Invincible.” His rapid aging and loyalty to Mark define his arc, exploring family and growth. Oliver’s youthful energy and Viltrumite power make him a dynamic Image Comics hero, balancing his alien heritage with a desire to protect Earth, fighting alongside Invincible with courage and potential.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10870.jpg', 
            'https://www.youtube.com/embed/3eU7bSc2U8o'),
            ('Darkwing', 
            'Darkwing, a vigilante in Image Comics, uses stealth and combat prowess to fight crime. With a mysterious past, he battles foes in “Savage Dragon,” echoing Batman’s style but with a grittier edge. His relentless pursuit of justice and shadowy methods make him compelling, navigating a world of corruption. Darkwing’s blend of skill and determination positions him as a street-level hero, delivering justice in the darkness with unwavering resolve.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1089.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Noble Causes', 
            'The Noble family, a superhero dynasty in Image Comics, wields varied powers, fighting for legacy and justice. Led by Doc Noble, they face internal drama and external threats, seen in “Noble Causes.” Their soap-opera dynamics and heroic deeds explore family and duty. Each member’s unique abilities and personal struggles make them a collective hero, balancing personal conflicts with epic battles, redefining heroism through unity and resilience in a complex world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1090.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Dynamo 5', 
            'Dynamo 5, a team of siblings in Image Comics, inherits diverse powers from Captain Dynamo, protecting Tower City. With abilities like telepathy, shape-shifting, and laser vision, they battle foes like Widowmaker, seen in “Dynamo 5.” Their dysfunctional family dynamic and teamwork explore unity and legacy. Each member’s growth into heroism makes Dynamo 5 a unique collective hero, blending individual strengths into a powerful unit fighting for justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1091.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Invincible Iron Man', 
            'An alternate Tony Stark, Invincible Iron Man wields advanced armor with repulsors and flight, fighting threats like the Mandarin. His genius and charisma mirror the mainline Iron Man, seen in “Invincible Iron Man,” but with unique twists. His technological innovations and leadership shine, exploring redemption and power. This variant’s blend of tech and heroism makes him a compelling Marvel hero, forging a legacy of innovation and courage in the face of adversity.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1004.jpg', 
            'https://www.youtube.com/embed/Ke1Y3P9D0Bc'),
            ('War Machine', 
            'James “Rhodey” Rhodes, a Marine and Tony Stark’s friend, became War Machine, wielding a militarized Iron Man suit with heavy weaponry. Fighting foes like Titanium Man and AIM, his loyalty shines in “Iron Man” and “Avengers.” Rhodey’s discipline and courage, seen in “War Machine,” make him a grounded hero. His journey explores friendship and duty, balancing military precision with heroism, making him a key Marvel figure delivering justice with firepower.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/149.jpg', 
            'https://www.youtube.com/embed/Ke1Y3P9D0Bc'),
            ('Falcon', 
            'Sam Wilson, a former social worker, became Falcon with a winged suit and Redwing, a telepathic drone. Later Captain America, he fights Hydra and Red Skull, seen in “Captain America: Sam Wilson.” His empathy and leadership shine in the Avengers, balancing aerial agility with street-level grit. Sam’s journey explores community and legacy, making him a vital Marvel hero who soars with courage and heart, uplifting those around him.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/73.jpg', 
            'https://www.youtube.com/embed/8zQvk2L8dMo'),
            ('Ms. Marvel', 
            'Kamala Khan, a Pakistani-American teen from Jersey City, gained polymorphic powers from Terrigen Mists, becoming Ms. Marvel. With shape-shifting and healing, she fights villains like the Inventor, seen in “Ms. Marvel.” Her fangirl enthusiasm for Captain Marvel and youthful optimism shine, balancing heroism with high school life. Kamala’s cultural identity and determination make her a modern Marvel icon, inspiring diversity and resilience in the fight for justice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/10366.jpg', 
            'https://www.youtube.com/embed/m9EX0f6V11Y'),
            ('Moon Knight', 
            'Marc Spector, a mercenary revived by the Egyptian god Khonshu, became Moon Knight, wielding lunar-enhanced strength and crescent darts. Fighting foes like Bushman and Midnight, his fractured psyche—housing multiple personalities—shines in “Moon Knight.” His gritty vigilantism and spiritual struggle explore identity and redemption. Moon Knight’s blend of mysticism, combat, and psychological depth makes him a unique Marvel hero, delivering justice under the moon’s glow with relentless ferocity.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/94.jpg', 
            'https://www.youtube.com/embed/x7KR88i1Z-o'),
            ('Blade', 
            'Eric Brooks, born to a mother bitten by a vampire, became Blade, a vampire hunter with superhuman strength and agility. Wielding swords and stakes, he battles Dracula and Deacon Frost, seen in “Blade.” His half-human, half-vampire nature fuels his relentless crusade, balancing humanity with his dark side. Blade’s gritty heroism and supernatural expertise make him a Marvel icon, cutting through evil with precision and a brooding intensity that defines his legacy.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/48.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Iron Fist', 
            'Danny Rand, trained in the mystical city of K’un-Lun, became Iron Fist, channeling chi into a glowing fist for superhuman strikes. Fighting foes like Steel Serpent, his martial arts mastery shines in “Iron Fist” and “Defenders.” His spiritual journey and quest for balance define his arc, blending mysticism with street-level heroism. Danny’s discipline and heart make him a unique Marvel hero, punching through evil with chi-powered precision and unwavering resolve.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/84.jpg', 
            'https://www.youtube.com/embed/f9OKL5no-S0'),
            ('Luke Cage', 
            'Carl Lucas, framed and imprisoned, gained unbreakable skin and super strength from an experimental procedure, becoming Luke Cage, Power Man. Protecting Harlem from foes like Diamondback and Bushmaster, his street-level heroism shines in “Luke Cage” and “Heroes for Hire.” His community focus and resilience, rooted in his unjust past, make him a Marvel stalwart. Luke’s blend of invulnerability and heart defines his role, fighting for justice with unyielding strength and a protector’s spirit.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/90.jpg', 
            'https://www.youtube.com/embed/ytkjQvSkNqo'),
            ('Nova', 
            'Richard Rider, a teen chosen by the Nova Corps, gained super strength, flight, and energy projection as Nova, wielding the Nova Force. Protecting Earth and the galaxy from Annihilus and the Cancerverse, his arc in “Annihilation” shines. Richard’s growth from rookie to leader defines his heroism, blending cosmic power with human grit. Nova’s interstellar battles and courage make him a Marvel hero, soaring through the stars with unyielding determination.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/105.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('She-Hulk', 
            'Jennifer Walters, a lawyer, gained gamma-powered strength and green skin after a blood transfusion from Bruce Banner, becoming She-Hulk. Balancing her legal career with heroism, she fights foes like Titania, seen in “She-Hulk” and “Sensational She-Hulk.” Her wit, confidence, and breaking of the fourth wall make her a fan-favorite. Jennifer’s journey explores empowerment and identity, making her a vibrant Marvel hero who smashes villains and stereotypes with equal force, radiating strength and charm.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/125.jpg', 
            'https://www.youtube.com/embed/u7JsKhI2An0'),
            ('Sentry', 
            'Robert Reynolds, a troubled man, gained the power of a million exploding suns from a super-serum, becoming the Sentry. With godlike strength, flight, and energy manipulation, he battles Void, his dark counterpart, in “Sentry” and “Dark Avengers.” His mental instability and immense power explore heroism and fragility. The Sentry’s struggle to control his godlike abilities makes him a tragic Marvel hero, shining brightly while wrestling with inner darkness in epic battles.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/123.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Human Torch', 
            'Johnny Storm, a member of the Fantastic Four, gained flame powers from cosmic radiation, becoming the Human Torch. Controlling fire and flight, he battles Doctor Doom and Galactus, seen in “Fantastic Four.” His brash personality and loyalty to his team shine, balancing youth with heroism. Johnny’s fiery spirit and growth in “Ultimate Fantastic Four” make him a dynamic Marvel hero, blazing through threats with charisma and power, lighting up the team’s adventures.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/82.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Invisible Woman', 
            'Sue Storm, a Fantastic Four founder, gained invisibility and force field powers from cosmic radiation. As Invisible Woman, she protects her team from threats like Doctor Doom, seen in “Fantastic Four” and “Civil War.” Her nurturing yet fierce nature, plus her romance with Reed Richards, defines her arc. Sue’s strategic mind and resilience make her a vital Marvel hero, shielding allies with unbreakable fields and proving her strength lies in both power and compassion.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/81.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Mr. Fantastic', 
            'Reed Richards, a genius scientist, gained elasticity from cosmic radiation, becoming Mr. Fantastic of the Fantastic Four. Stretching his body and intellect, he battles Doctor Doom and the Skrulls, seen in “Secret Invasion.” His leadership and curiosity drive the team, though his obsession with science strains his family. Reed’s blend of brain and flexibility makes him a Marvel cornerstone, solving cosmic mysteries and fighting threats with innovative heroism and unwavering dedication.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/95.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Thing', 
            'Ben Grimm, a pilot turned rock-like hero by cosmic radiation, became the Thing, with immense strength and durability. A Fantastic Four stalwart, he battles Doctor Doom and Galactus, seen in “Fantastic Four.” His gruff exterior hides a loyal heart, grappling with his monstrous appearance. Ben’s resilience and humor shine in “Clobberin’ Time,” making him a beloved Marvel hero. His journey explores self-acceptance, proving true strength lies in heart and grit, not just muscle.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/139.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Cyclops', 
            'Scott Summers, an X-Men leader, fires optic energy blasts due to a mutant gene, controlled by a ruby quartz visor. Facing Magneto and Sentinels, his strategic mind shines in “Astonishing X-Men” and “Schism.” His romance with Jean Grey and leadership struggles define his arc, balancing duty with personal loss. Cyclops’ discipline and vision make him a core Marvel mutant, fighting for coexistence with unyielding focus, leading the X-Men through a world of prejudice.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/66.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Iceman', 
            'Bobby Drake, a mutant with ice manipulation, creates frozen constructs and lowers temperatures as an X-Men member. Facing foes like the Brotherhood of Mutants, his playful demeanor shines in “X-Men: First Class” and “All-New X-Men.” His journey explores identity and power, embracing his omega-level potential. Iceman’s humor and resilience make him a dynamic Marvel hero, freezing threats with creativity and heart, proving his cool exterior hides a fiery spirit.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/153.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Beast', 
            'Hank McCoy, a brilliant scientist and X-Men member, gained animal-like strength and agility from his mutant genes. His blue-furred form and intellect shine against foes like Magneto, seen in “X-Men: Days of Future Past.” Hank’s struggle with his beastly appearance and moral dilemmas define his arc, exploring science and humanity. Beast’s compassion and genius make him a vital Marvel hero, leaping into battle with both brain and brawn, fighting for mutant rights.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/43.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Colossus', 
            'Piotr Rasputin, a Russian mutant, transforms into organic steel with super strength as an X-Men member. Facing Juggernaut and Omega Red, his gentle soul shines in “Deadpool” and “Astonishing X-Men.” His loyalty to his sister Illyana and the X-Men defines his arc, exploring sacrifice and duty. Colossus’ resilience and heart make him a Marvel stalwart, standing firm as a metallic protector, fighting for a world that fears mutants with unyielding strength.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/61.jpg', 
            'https://www.youtube.com/embed/Div0iP65aZo'),
            ('Rogue', 
            'Anna Marie, a mutant with power absorption through touch, joined the X-Men after a troubled youth. Stealing abilities and memories, she battles Mystique and Sentinels, seen in “X-Men” and “Rogue & Gambit.” Her romance with Gambit and struggle with her uncontrollable powers explore identity and connection. Rogue’s Southern charm and resilience make her a beloved Marvel hero, fighting for control and acceptance, absorbing threats with courage and heart in a mutant world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/121.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Kitty Pryde', 
            'Kitty Pryde, a mutant with intangibility, phases through objects as an X-Men member. Facing Sentinels and the Brotherhood, her wit and courage shine in “Days of Future Past” and “Astonishing X-Men.” Her bond with Colossus and mentorship under Storm define her arc, exploring growth and leadership. Kitty’s tech-savvy nature and youthful spirit make her a dynamic Marvel hero, phasing through danger with intelligence and heart, protecting mutants with fearless determination.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/89.jpg', 
            'https://www.youtube.com/embed/7p6MHO0hRY4'),
            ('Starfire', 
            'Koriand’r, a Tamaranean princess, wields energy blasts and flight, escaping slavery to join the Teen Titans. Facing Blackfire and Trigon, her optimistic spirit shines in “Teen Titans” and “Titans.” Her romance with Dick Grayson and alien perspective explore freedom and belonging. Starfire’s radiant energy and compassion make her a vibrant DC hero, soaring through battles with fiery power and a heart that lights up her team and the universe.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1105.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Raven', 
            'Rachel Roth, daughter of the demon Trigon, wields empathic and magical powers as a Teen Titan. Battling her father and inner darkness, her arc in “Teen Titans” and “Terror of Trigon” explores control and redemption. Her mystical knowledge and quiet strength shine, balancing light and shadow. Raven’s emotional depth and sacrifice make her a compelling DC hero, weaving magic and empathy to protect her friends and the world from demonic threats.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1104.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Beast Boy', 
            'Garfield Logan, a Teen Titan, gained shape-shifting from an experimental cure, transforming into any animal. Fighting Slade and the Brotherhood of Evil, his humor shines in “Teen Titans” and “Young Justice.” His playful nature and loyalty to his team explore friendship and growth. Beast Boy’s versatility and heart make him a dynamic DC hero, leaping into battle with animalistic prowess and a grin, proving joy can be a powerful weapon.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/1106.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Robin', 
            'Tim Drake, the third Robin, became Batman’s protégé through detective skills and determination, wielding bo staff and tech. Fighting Ra’s al Ghul and the Court of Owls, his arc in “Robin” and “Teen Titans” explores intellect and legacy. His leadership and loyalty shine, balancing Batman’s shadow with his own path. Tim’s analytical mind and courage make him a key DC hero, proving brain and bravery can match any superpower in Gotham’s fight.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/850.jpg', 
            'https://www.youtube.com/embed/1o-4aV5nJZs'),
            ('Supergirl', 
            'Kara Zor-El, Superman’s cousin, escaped Krypton’s destruction, gaining super strength, flight, and heat vision on Earth. Protecting National City from foes like Reign, her arc in “Supergirl” explores hope and identity. Her optimism and Kryptonian heritage shine, balancing heroism with her life as Kara Danvers. A Justice League member, Supergirl’s compassion and power make her a radiant DC hero, soaring with the same heart as Superman, fighting for truth and justice with unwavering spirit.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/792.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Power Girl', 
            'Kara Zor-L, an alternate Supergirl from Earth-2, wields Kryptonian powers like super strength and flight. Fighting Ultra-Humanite, her arc in “Justice Society” explores legacy and resilience. Her bold personality and leadership shine, balancing her Earth-2 roots with Earth-1 challenges. Power Girl’s strength and confidence make her a standout DC hero, punching through threats with Kryptonian might and a fierce determination to protect her adopted world.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/763.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Booster Gold', 
            'Michael Jon Carter, a 25th-century athlete, stole tech to become Booster Gold, a time-traveling hero with energy blasts and flight. Fighting Maxwell Lord, his arc in “52” and “Justice League International” explores fame and heroism. His brash charm and growth into a true hero shine, balancing ego with sacrifice. Booster’s futuristic tech and heart make him a unique DC hero, leaping through time to save the day with flair and courage.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/668.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o'),
            ('Vixen', 
            'Mari McCabe, a model, wields a mystical Tantu Totem, channeling animal powers like a cheetah’s speed or elephant’s strength. Fighting poachers and Anansi, her arc in “Justice League Unlimited” explores heritage and justice. Her African roots and fierce spirit shine, balancing fashion with heroism. Vixen’s versatility and compassion make her a vibrant DC hero, harnessing nature’s power to protect the world with grace and ferocity.', 
            'https://www.superherodb.com/pictures2/portraits/10/100/803.jpg', 
            'https://www.youtube.com/embed/4kS2b7v3f0o')
        ]
        c.executemany('INSERT INTO superheroes (name, description, image_url, video_url) VALUES (?, ?, ?, ?)', heroes)
    conn.commit()
    conn.close()

def add_user(username, email, password):
    #connect to the databse
    #have an active cursor
    #execute instruction, I am adding a user so I will be using INSERT INTO user...etc
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    try:
        c.execute('INSERT INTO users (username, email, password) VALUES (?, ?, ?)',
                  (username, email, password))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False
    finally:
        conn.close()

def check_user(email, password):
    #connect to the databse
    #have an active cursor
    #execute instruction, I am validating a user's credentials when they log in/sign in
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute('SELECT id, username FROM users WHERE email = ? AND password = ?', (email, password))
    user = c.fetchone() #this returns a dictionary, and its now being assigned to a variable called user
    conn.close()
    if user:
        return {'id': user[0], 'username': user[1]}#this is for the session management
    return None

def get_all_superheroes():
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute('SELECT id, name, description, image_url FROM superheroes')
    #This is another way to write if statements in python, it's effiecient and saves time and space in the coding environment
    #it would have been 
    # for row in c.fetchall():
    #     id=row[0]
    #     name=row[1]
    #     desc=row[2]
    #     img=row[3]
    #     heroes={"id":id,"name":name,"desc":desc,"img":img} this is a dicionary
    heroes = [{'id': row[0], 'name': row[1], 'description': row[2], 'image_url': row[3]} for row in c.fetchall()]
    conn.close()
    return heroes

def get_superhero(hero_id):
    conn = sqlite3.connect('database.db')
    c = conn.cursor()
    c.execute('SELECT id, name, description, image_url, video_url FROM superheroes WHERE id = ?', (hero_id,))
    hero = c.fetchone()
    conn.close()
    if hero:
        return {'id': hero[0], 'name': hero[1], 'description': hero[2], 'image_url': hero[3], 'video_url': hero[4]}
    return None